title: "Xinlei Lin"
author: "Xinlei Lin"
description: "New York University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "projects.html", title: "Projects"}
  - {file: "publications.md", title: "Publications and Conferences"}
  - {file: "resume.pdf", title: "Resume"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:xl1005@nyu.edu"}
  - {title: Github, icon: github, url: "https://github.com/daisilin"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/leixlin"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
