title: "Shilei Peng (SrayPen)"
author: "Shilei Peng"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About"}
  - {file: "resume.md", title: "CV"}
  - {file: "publications.md", title: "Publications"}
  - {file: "projects.md", title: "Activities"}

  # - {url: "/daisy_resume.pdf", title: "Resume"}
#   - {file: "talks.html", title: "Talks"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "pengshilei@isa.ac.cn"}
  # - {title: ReswarchGate, icon: github, url: "https://github.com/daisilin"}
  # - {title: Twitter, icon: twitter, url: "https://twitter.com/leixlin"}
  # - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/xinlei-lin-in"}

comments:
 # disqus_shortname: ""    # see https://disqus.com/
 # isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
